#                                                 # Numpy

In [1]:
# import the numpy as np

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
print(np.__version__)

1.19.2


# NumPy Creating Arrays

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, 
#and it will be converted into an ndarray:

In [4]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


# 0-D Arrays

In [5]:
import numpy as np

arr = np.array(22)

print(arr)

22


In [6]:
arr = np.array(17)

print(arr)

17


# 1-D Arrays

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 2-D Arrays

In [8]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


# 3-D arrays

In [9]:

arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [10]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
# Check how many dimensions the arrays have
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])

print(a.ndim)
print(b.ndim)

0
1


In [12]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# NumPy Array Indexing

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [14]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [15]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [16]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [17]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


In [22]:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [23]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [24]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 1nd dim: ', arr[0, -1])

Last element from 1nd dim:  5


# NumPy Array Slicing 

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:5])

[3 4 5]


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:])

[3 4 5 6 7]


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-5:-1])

[3 4 5 6]


In [29]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [30]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [31]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]
